# Generated by Django 4.2.5 on 2023-10-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=50)),
                ('e_desgn', models.CharField(max_length=50)),
                ('e_location', models.CharField(max_length=200)),
                ('e_phn', models.CharField(max_length=20)),
                ('e_post', models.CharField(max_length=200)),
                ('post_date', models.DateField()),
            ],
        ),
    ]
